name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          type: wide
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_filename: assets/devcard.png
          commit_message: "chore: update ${filename}"
